spring:
  application:
    name: Courier-Management
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  datasource:
    url: jdbc:postgresql://localhost:5432/courierdb
    username: postgres
    password: aluno

server:
  port: 8081